// <auto-generated />
using System;
using BolDeSangManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BolDeSangManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260909214002_SupprimerValeurActuelleJoueur")]
    partial class SupprimerValeurActuelleJoueur
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("BolDeSangManager.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JetonCalendrier")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PseudoCoach")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SupprimeLe")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupprimePar")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.AppConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Valeur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppConfigs");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.Division", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordre")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.ToTable("Divisions");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.EcheanceRonde", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateLimite")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ronde")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId", "Ronde")
                        .IsUnique();

                    b.ToTable("EcheancesRondes");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.Inducement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cout")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordre")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantiteMax")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Restriction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RulesVersionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RulesVersionId", "Nom")
                        .IsUnique();

                    b.ToTable("Inducements");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BudgetDepart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommissaireId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Format")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ModeBrouillard")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NombreEquipesPlayoff")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsDefaite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsNul")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsParAgression")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsParDeviation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsParElimination")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsParInterception")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsParPasse")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsParTouchdown")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsVictoire")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reglement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RulesVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XpBonusMvp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XpParAgression")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XpParDeviation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XpParElimination")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XpParInterception")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XpParPasse")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XpParTouchdown")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommissaireId");

                    b.HasIndex("GameId");

                    b.HasIndex("RulesVersionId");

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.LeagueAward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AttribueLe")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoachId")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.HasIndex("LeagueId");

                    b.HasIndex("TeamId");

                    b.HasIndex("TeamPlayerId");

                    b.ToTable("LeagueAwards");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.LeagueCommissioner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssigneLe")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignePar")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("LeagueId", "UserId")
                        .IsUnique();

                    b.ToTable("LeagueCommissioners");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.LeagueStaffType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CompteDansVea")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cout")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CoutDepuisTypeEquipe")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstActif")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxCreation")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxLigue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinCreation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordre")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StaffTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.HasIndex("StaffTypeId");

                    b.ToTable("LeagueStaffTypes");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateJouee")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateProgrammee")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DivisionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipeDomicileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipeExterieurId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstPlayoff")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lieu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ronde")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ScoreDomicile")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ScoreExterieur")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.HasIndex("EquipeDomicileId");

                    b.HasIndex("EquipeExterieurId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.MatchPlayerRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AManqueLeMatch")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agressions")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Blessure")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Deviations")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EliminationsInfligees")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstCoteDomicile")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstMVP")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Interceptions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchSheetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Passes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PspGagnes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StatAffectee")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Touchdowns")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchSheetId");

                    b.HasIndex("TeamPlayerId");

                    b.ToTable("MatchPlayerRecords");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.MatchSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ApresMatchDomicileValide")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ApresMatchExterieurValide")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfirmeeParCommissaire")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConfirmeeParCommissaireLe")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CorrigeeLe")
                        .HasColumnType("TEXT");

                    b.Property<int>("EliminationsDomicile")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EliminationsExterieur")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GainsDomicile")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GainsExterieur")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InducementsDomicile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InducementsExterieur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NombreDeTours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NotesCommissaire")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SaisiLe")
                        .HasColumnType("TEXT");

                    b.Property<string>("SaisiParId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ScoreAvantCorrectionDomicile")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ScoreAvantCorrectionExterieur")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TouchdownsDomicile")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TouchdownsExterieur")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ValideParCommissaire")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VariationFansDomicile")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VariationFansDomicileAppliquee")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VariationFansExterieur")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VariationFansExterieurAppliquee")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.HasIndex("SaisiParId");

                    b.ToTable("MatchSheets");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.PalierAmeliorationPsp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoutAleaPrincipale")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoutCaracteristique")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoutChoixPrincipale")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoutSecondaire")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rang")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RulesVersionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RulesVersionId", "Rang")
                        .IsUnique();

                    b.ToTable("PaliersAmelioration");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.PalierPointsLigue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("APartirDuTour")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsDefaite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsNul")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsVictoire")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId", "APartirDuTour")
                        .IsUnique();

                    b.ToTable("PaliersPointsLigue");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.PhaseDeReposValidation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ValideLe")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("LeagueId", "TeamId")
                        .IsUnique();

                    b.ToTable("PhaseDeReposValidations");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.PlayerImprovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AppliqueLe")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnAttenteValidation")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MatchSheetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Palier")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SkillId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StatAmelioree")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ValeurHausse")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XpDepensee")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchSheetId");

                    b.HasIndex("SkillId");

                    b.HasIndex("TeamPlayerId");

                    b.ToTable("PlayerImprovements");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.PlayerInjury", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StatAffectee")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("TeamPlayerId");

                    b.ToTable("PlayerInjuries");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.PlayerPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Agilite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Armure")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CapacitePasse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Cout")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Force")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MotsCles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Mouvement")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantiteMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamTypeId");

                    b.ToTable("PlayerPositions");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.PlayerPositionCategoryAccess", b =>
                {
                    b.Property<int>("PlayerPositionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillCategoryDefId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstPrincipale")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerPositionId", "SkillCategoryDefId");

                    b.HasIndex("SkillCategoryDefId");

                    b.ToTable("PlayerPositionCategoryAccesses");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.PlayerPositionSkill", b =>
                {
                    b.Property<int>("PlayerPositionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerPositionId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("PlayerPositionSkills");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.PoolPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Agilite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Armure")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CapacitePasse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Cout")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Force")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MotsCles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Mouvement")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantiteMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RulesVersionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RulesVersionId");

                    b.ToTable("PoolPositions");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.PoolPositionCategoryAccess", b =>
                {
                    b.Property<int>("PoolPositionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillCategoryDefId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstPrincipale")
                        .HasColumnType("INTEGER");

                    b.HasKey("PoolPositionId", "SkillCategoryDefId");

                    b.HasIndex("SkillCategoryDefId");

                    b.ToTable("PoolPositionCategoryAccesses");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.PoolPositionSkill", b =>
                {
                    b.Property<int>("PoolPositionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PoolPositionId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("PoolPositionSkills");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.RulesVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DernierExportLe")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HausseAgilite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HausseArmure")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HausseCapacitePasse")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HausseForce")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HausseMouvement")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HaussePrincipale")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HausseSecondaire")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordre")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsDefaite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsNul")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsParAgression")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsParDeviation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsParElimination")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsParInterception")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsParPasse")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsParTouchdown")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsVictoire")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SurcoutElite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XpBonusMvp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XpParAgression")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XpParDeviation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XpParElimination")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XpParInterception")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XpParPasse")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XpParTouchdown")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("RulesVersions");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Categorie")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstElite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstTrait")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RulesVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillCategoryDefId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RulesVersionId");

                    b.HasIndex("SkillCategoryDefId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.SkillCategoryDef", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RulesVersionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RulesVersionId", "Code")
                        .IsUnique();

                    b.HasIndex("RulesVersionId", "Nom")
                        .IsUnique();

                    b.ToTable("SkillCategories");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.SpecialRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordre")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RulesVersionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RulesVersionId", "Nom")
                        .IsUnique();

                    b.ToTable("SpecialRules");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.StaffDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CompteDansVea")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cout")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CoutDepuisTypeEquipe")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstActif")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxCreation")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxLigue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinCreation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordre")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RulesVersionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RulesVersionId");

                    b.ToTable("StaffTypes");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.StarPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Agilite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Armure")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CapacitePasse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Competences")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Cout")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Force")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mouvement")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordre")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReglesSpeciales")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RulesVersionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RulesVersionId", "Nom")
                        .IsUnique();

                    b.ToTable("StarPlayers");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.StarPlayerThemedLeague", b =>
                {
                    b.Property<int>("StarPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThemedLeagueId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StarPlayerId", "ThemedLeagueId");

                    b.HasIndex("ThemedLeagueId");

                    b.ToTable("StarPlayerThemedLeague");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Apothicaire")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoachId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiviniteChoisie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DivisionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EliminationsInfligees")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FansDevoues")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NombreCheerleaders")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NombreCoachsAssistants")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NombreDefaites")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NombreMatchsJoues")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NombreNuls")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NombreRelances")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NombreVictoires")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsLigue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TouchdownsConcedes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TouchdownsMarques")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tresorerie")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.HasIndex("DivisionId");

                    b.HasIndex("LeagueId");

                    b.HasIndex("TeamTypeId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.TeamPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstCapitaine")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstMort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstRetraite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ManqueSuivantMatch")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModAgilite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModArmure")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModCapacitePasse")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModForce")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModMouvement")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerPositionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsStarPlayer")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RecrueGratuiteMatchId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecruteLe")
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerPositionId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamPlayers");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.TeamPlayerSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnAttenteValidation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstCompetenceDepart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamPlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("TeamPlayerId");

                    b.ToTable("TeamPlayerSkills");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.TeamStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeagueStaffTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LeagueStaffTypeId");

                    b.HasIndex("TeamId", "LeagueStaffTypeId")
                        .IsUnique();

                    b.ToTable("TeamStaffs");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.TeamType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Categorie")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CategorieLrb");

                    b.Property<int>("CoutRelance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LiguesTexteObsolete")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ReglesSpecialesLigue");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReglesSpeciales")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RulesVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StyleJeuObsolete")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Categorie");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("RulesVersionId");

                    b.ToTable("TeamTypes");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.TeamTypeKeywordLimit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Max")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MotCle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamTypeId");

                    b.ToTable("TeamTypeKeywordLimits");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.TeamTypeSpecialRule", b =>
                {
                    b.Property<int>("TeamTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpecialRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LimiteParApresMatch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OptionsChoix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TeamTypeId", "SpecialRuleId");

                    b.HasIndex("SpecialRuleId");

                    b.ToTable("TeamTypeSpecialRules");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.TeamTypeThemedLeague", b =>
                {
                    b.Property<int>("TeamTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThemedLeagueId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TeamTypeId", "ThemedLeagueId");

                    b.HasIndex("ThemedLeagueId");

                    b.ToTable("TeamTypeThemedLeague");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.ThemedLeague", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordre")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RulesVersionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RulesVersionId", "Nom")
                        .IsUnique();

                    b.ToTable("ThemedLeagues");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.XpCorrection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AncienneValeur")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CorrigeLe")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrigeParId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NouvelleValeur")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamPlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CorrigeParId");

                    b.HasIndex("TeamPlayerId");

                    b.ToTable("XpCorrections");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.Division", b =>
                {
                    b.HasOne("BolDeSangManager.Data.Models.League", "League")
                        .WithMany("Divisions")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.EcheanceRonde", b =>
                {
                    b.HasOne("BolDeSangManager.Data.Models.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.Inducement", b =>
                {
                    b.HasOne("BolDeSangManager.Data.Models.RulesVersion", "RulesVersion")
                        .WithMany()
                        .HasForeignKey("RulesVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RulesVersion");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.League", b =>
                {
                    b.HasOne("BolDeSangManager.Data.ApplicationUser", "Commissaire")
                        .WithMany("LiguesCommissaireees")
                        .HasForeignKey("CommissaireId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BolDeSangManager.Data.Models.Game", "Game")
                        .WithMany("Ligues")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BolDeSangManager.Data.Models.RulesVersion", "RulesVersion")
                        .WithMany()
                        .HasForeignKey("RulesVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commissaire");

                    b.Navigation("Game");

                    b.Navigation("RulesVersion");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.LeagueAward", b =>
                {
                    b.HasOne("BolDeSangManager.Data.ApplicationUser", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BolDeSangManager.Data.Models.League", "League")
                        .WithMany("Awards")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BolDeSangManager.Data.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BolDeSangManager.Data.Models.TeamPlayer", "TeamPlayer")
                        .WithMany()
                        .HasForeignKey("TeamPlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Coach");

                    b.Navigation("League");

                    b.Navigation("Team");

                    b.Navigation("TeamPlayer");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.LeagueCommissioner", b =>
                {
                    b.HasOne("BolDeSangManager.Data.Models.League", "League")
                        .WithMany("CommissairesDeLigue")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BolDeSangManager.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.LeagueStaffType", b =>
                {
                    b.HasOne("BolDeSangManager.Data.Models.League", "League")
                        .WithMany("StaffTypes")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BolDeSangManager.Data.Models.StaffDefinition", "StaffDefinition")
                        .WithMany()
                        .HasForeignKey("StaffTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("League");

                    b.Navigation("StaffDefinition");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.Match", b =>
                {
                    b.HasOne("BolDeSangManager.Data.Models.Division", "Division")
                        .WithMany("Matchs")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BolDeSangManager.Data.Models.Team", "EquipeDomicile")
                        .WithMany()
                        .HasForeignKey("EquipeDomicileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BolDeSangManager.Data.Models.Team", "EquipeExterieur")
                        .WithMany()
                        .HasForeignKey("EquipeExterieurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Division");

                    b.Navigation("EquipeDomicile");

                    b.Navigation("EquipeExterieur");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.MatchPlayerRecord", b =>
                {
                    b.HasOne("BolDeSangManager.Data.Models.MatchSheet", "MatchSheet")
                        .WithMany("RecordsJoueurs")
                        .HasForeignKey("MatchSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BolDeSangManager.Data.Models.TeamPlayer", "TeamPlayer")
                        .WithMany("RecordsMatchs")
                        .HasForeignKey("TeamPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchSheet");

                    b.Navigation("TeamPlayer");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.MatchSheet", b =>
                {
                    b.HasOne("BolDeSangManager.Data.Models.Match", "Match")
                        .WithOne("Feuille")
                        .HasForeignKey("BolDeSangManager.Data.Models.MatchSheet", "MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BolDeSangManager.Data.ApplicationUser", "SaisiPar")
                        .WithMany()
                        .HasForeignKey("SaisiParId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("SaisiPar");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.PalierAmeliorationPsp", b =>
                {
                    b.HasOne("BolDeSangManager.Data.Models.RulesVersion", "RulesVersion")
                        .WithMany("PaliersAmelioration")
                        .HasForeignKey("RulesVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RulesVersion");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.PalierPointsLigue", b =>
                {
                    b.HasOne("BolDeSangManager.Data.Models.League", "League")
                        .WithMany("PaliersPoints")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.PhaseDeReposValidation", b =>
                {
                    b.HasOne("BolDeSangManager.Data.Models.League", "League")
                        .WithMany("ValidationsRepos")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BolDeSangManager.Data.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.PlayerImprovement", b =>
                {
                    b.HasOne("BolDeSangManager.Data.Models.MatchSheet", "MatchSheet")
                        .WithMany()
                        .HasForeignKey("MatchSheetId");

                    b.HasOne("BolDeSangManager.Data.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BolDeSangManager.Data.Models.TeamPlayer", "TeamPlayer")
                        .WithMany("Improvements")
                        .HasForeignKey("TeamPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchSheet");

                    b.Navigation("Skill");

                    b.Navigation("TeamPlayer");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.PlayerInjury", b =>
                {
                    b.HasOne("BolDeSangManager.Data.Models.Match", "Match")
                        .WithMany("Blessures")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BolDeSangManager.Data.Models.TeamPlayer", "TeamPlayer")
                        .WithMany("Blessures")
                        .HasForeignKey("TeamPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("TeamPlayer");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.PlayerPosition", b =>
                {
                    b.HasOne("BolDeSangManager.Data.Models.TeamType", "TeamType")
                        .WithMany("Postes")
                        .HasForeignKey("TeamTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamType");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.PlayerPositionCategoryAccess", b =>
                {
                    b.HasOne("BolDeSangManager.Data.Models.PlayerPosition", "PlayerPosition")
                        .WithMany("AccesCategories")
                        .HasForeignKey("PlayerPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BolDeSangManager.Data.Models.SkillCategoryDef", "SkillCategoryDef")
                        .WithMany()
                        .HasForeignKey("SkillCategoryDefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlayerPosition");

                    b.Navigation("SkillCategoryDef");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.PlayerPositionSkill", b =>
                {
                    b.HasOne("BolDeSangManager.Data.Models.PlayerPosition", "PlayerPosition")
                        .WithMany("CompetencesDepart")
                        .HasForeignKey("PlayerPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BolDeSangManager.Data.Models.Skill", "Skill")
                        .WithMany("PositionsAvecCompetence")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerPosition");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.PoolPosition", b =>
                {
                    b.HasOne("BolDeSangManager.Data.Models.RulesVersion", "RulesVersion")
                        .WithMany("PoolPositions")
                        .HasForeignKey("RulesVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RulesVersion");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.PoolPositionCategoryAccess", b =>
                {
                    b.HasOne("BolDeSangManager.Data.Models.PoolPosition", "PoolPosition")
                        .WithMany("AccesCategories")
                        .HasForeignKey("PoolPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BolDeSangManager.Data.Models.SkillCategoryDef", "SkillCategoryDef")
                        .WithMany()
                        .HasForeignKey("SkillCategoryDefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PoolPosition");

                    b.Navigation("SkillCategoryDef");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.PoolPositionSkill", b =>
                {
                    b.HasOne("BolDeSangManager.Data.Models.PoolPosition", "PoolPosition")
                        .WithMany("CompetencesDepart")
                        .HasForeignKey("PoolPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BolDeSangManager.Data.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PoolPosition");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.RulesVersion", b =>
                {
                    b.HasOne("BolDeSangManager.Data.Models.Game", "Game")
                        .WithMany("Versions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.Skill", b =>
                {
                    b.HasOne("BolDeSangManager.Data.Models.RulesVersion", "RulesVersion")
                        .WithMany()
                        .HasForeignKey("RulesVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BolDeSangManager.Data.Models.SkillCategoryDef", "SkillCategoryDef")
                        .WithMany("Competences")
                        .HasForeignKey("SkillCategoryDefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RulesVersion");

                    b.Navigation("SkillCategoryDef");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.SkillCategoryDef", b =>
                {
                    b.HasOne("BolDeSangManager.Data.Models.RulesVersion", "RulesVersion")
                        .WithMany()
                        .HasForeignKey("RulesVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RulesVersion");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.SpecialRule", b =>
                {
                    b.HasOne("BolDeSangManager.Data.Models.RulesVersion", "RulesVersion")
                        .WithMany()
                        .HasForeignKey("RulesVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RulesVersion");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.StaffDefinition", b =>
                {
                    b.HasOne("BolDeSangManager.Data.Models.RulesVersion", "RulesVersion")
                        .WithMany("StaffTypes")
                        .HasForeignKey("RulesVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RulesVersion");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.StarPlayer", b =>
                {
                    b.HasOne("BolDeSangManager.Data.Models.RulesVersion", "RulesVersion")
                        .WithMany()
                        .HasForeignKey("RulesVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RulesVersion");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.StarPlayerThemedLeague", b =>
                {
                    b.HasOne("BolDeSangManager.Data.Models.StarPlayer", "StarPlayer")
                        .WithMany("Ligues")
                        .HasForeignKey("StarPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BolDeSangManager.Data.Models.ThemedLeague", "ThemedLeague")
                        .WithMany("StarPlayers")
                        .HasForeignKey("ThemedLeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StarPlayer");

                    b.Navigation("ThemedLeague");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.Team", b =>
                {
                    b.HasOne("BolDeSangManager.Data.ApplicationUser", "Coach")
                        .WithMany("Equipes")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BolDeSangManager.Data.Models.Division", "Division")
                        .WithMany("Equipes")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BolDeSangManager.Data.Models.League", "League")
                        .WithMany("Equipes")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BolDeSangManager.Data.Models.TeamType", "TeamType")
                        .WithMany("Equipes")
                        .HasForeignKey("TeamTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Division");

                    b.Navigation("League");

                    b.Navigation("TeamType");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.TeamPlayer", b =>
                {
                    b.HasOne("BolDeSangManager.Data.Models.PlayerPosition", "PlayerPosition")
                        .WithMany("Joueurs")
                        .HasForeignKey("PlayerPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BolDeSangManager.Data.Models.Team", "Team")
                        .WithMany("Joueurs")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerPosition");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.TeamPlayerSkill", b =>
                {
                    b.HasOne("BolDeSangManager.Data.Models.Skill", "Skill")
                        .WithMany("JoueursAvecCompetence")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BolDeSangManager.Data.Models.TeamPlayer", "TeamPlayer")
                        .WithMany("Competences")
                        .HasForeignKey("TeamPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("TeamPlayer");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.TeamStaff", b =>
                {
                    b.HasOne("BolDeSangManager.Data.Models.LeagueStaffType", "LeagueStaffType")
                        .WithMany("Achats")
                        .HasForeignKey("LeagueStaffTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BolDeSangManager.Data.Models.Team", "Team")
                        .WithMany("Staff")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeagueStaffType");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.TeamType", b =>
                {
                    b.HasOne("BolDeSangManager.Data.Models.Game", "Game")
                        .WithMany("TypesEquipes")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BolDeSangManager.Data.Models.RulesVersion", "RulesVersion")
                        .WithMany()
                        .HasForeignKey("RulesVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("RulesVersion");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.TeamTypeKeywordLimit", b =>
                {
                    b.HasOne("BolDeSangManager.Data.Models.TeamType", "TeamType")
                        .WithMany("LimitesMotsCles")
                        .HasForeignKey("TeamTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamType");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.TeamTypeSpecialRule", b =>
                {
                    b.HasOne("BolDeSangManager.Data.Models.SpecialRule", "SpecialRule")
                        .WithMany("TeamTypes")
                        .HasForeignKey("SpecialRuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BolDeSangManager.Data.Models.TeamType", "TeamType")
                        .WithMany("ReglesSpecialesListe")
                        .HasForeignKey("TeamTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpecialRule");

                    b.Navigation("TeamType");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.TeamTypeThemedLeague", b =>
                {
                    b.HasOne("BolDeSangManager.Data.Models.TeamType", "TeamType")
                        .WithMany("LiguesListe")
                        .HasForeignKey("TeamTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BolDeSangManager.Data.Models.ThemedLeague", "ThemedLeague")
                        .WithMany("Equipes")
                        .HasForeignKey("ThemedLeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamType");

                    b.Navigation("ThemedLeague");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.ThemedLeague", b =>
                {
                    b.HasOne("BolDeSangManager.Data.Models.RulesVersion", "RulesVersion")
                        .WithMany()
                        .HasForeignKey("RulesVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RulesVersion");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.XpCorrection", b =>
                {
                    b.HasOne("BolDeSangManager.Data.ApplicationUser", "CorrigePar")
                        .WithMany()
                        .HasForeignKey("CorrigeParId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BolDeSangManager.Data.Models.TeamPlayer", "TeamPlayer")
                        .WithMany()
                        .HasForeignKey("TeamPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CorrigePar");

                    b.Navigation("TeamPlayer");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BolDeSangManager.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BolDeSangManager.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BolDeSangManager.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BolDeSangManager.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BolDeSangManager.Data.ApplicationUser", b =>
                {
                    b.Navigation("Equipes");

                    b.Navigation("LiguesCommissaireees");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.Division", b =>
                {
                    b.Navigation("Equipes");

                    b.Navigation("Matchs");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.Game", b =>
                {
                    b.Navigation("Ligues");

                    b.Navigation("TypesEquipes");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.League", b =>
                {
                    b.Navigation("Awards");

                    b.Navigation("CommissairesDeLigue");

                    b.Navigation("Divisions");

                    b.Navigation("Equipes");

                    b.Navigation("PaliersPoints");

                    b.Navigation("StaffTypes");

                    b.Navigation("ValidationsRepos");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.LeagueStaffType", b =>
                {
                    b.Navigation("Achats");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.Match", b =>
                {
                    b.Navigation("Blessures");

                    b.Navigation("Feuille");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.MatchSheet", b =>
                {
                    b.Navigation("RecordsJoueurs");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.PlayerPosition", b =>
                {
                    b.Navigation("AccesCategories");

                    b.Navigation("CompetencesDepart");

                    b.Navigation("Joueurs");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.PoolPosition", b =>
                {
                    b.Navigation("AccesCategories");

                    b.Navigation("CompetencesDepart");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.RulesVersion", b =>
                {
                    b.Navigation("PaliersAmelioration");

                    b.Navigation("PoolPositions");

                    b.Navigation("StaffTypes");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.Skill", b =>
                {
                    b.Navigation("JoueursAvecCompetence");

                    b.Navigation("PositionsAvecCompetence");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.SkillCategoryDef", b =>
                {
                    b.Navigation("Competences");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.SpecialRule", b =>
                {
                    b.Navigation("TeamTypes");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.StarPlayer", b =>
                {
                    b.Navigation("Ligues");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.Team", b =>
                {
                    b.Navigation("Joueurs");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.TeamPlayer", b =>
                {
                    b.Navigation("Blessures");

                    b.Navigation("Competences");

                    b.Navigation("Improvements");

                    b.Navigation("RecordsMatchs");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.TeamType", b =>
                {
                    b.Navigation("Equipes");

                    b.Navigation("LiguesListe");

                    b.Navigation("LimitesMotsCles");

                    b.Navigation("Postes");

                    b.Navigation("ReglesSpecialesListe");
                });

            modelBuilder.Entity("BolDeSangManager.Data.Models.ThemedLeague", b =>
                {
                    b.Navigation("Equipes");

                    b.Navigation("StarPlayers");
                });
#pragma warning restore 612, 618
        }
    }
}
